architecture: qwen
model_path: Qwen/Qwen2-VL-7B-Instruct
model:
  - torch_dtype: auto
preprocess:
  - resize: True
  - width: 336
  - height: 336
output_db: ../output/TaskSensitivity/LastToken/Qwen2-VL-7B-Instruct/Default.db
input_dir: ../data_local/people
prompt: ""
pooling_method: last
modules:
  - visual.merger
  - model.layers.0
  - model.layers.5
  - model.layers.10
  - model.layers.15
  - model.layers.20
  - model.layers.25
  - model.layers.27
  - model.norm

