architecture: qwen
model_path: Qwen/Qwen2-VL-7B-Instruct
model:
  - torch_dtype: auto
preprocess:
  - resize: True
  - width: 336
  - height: 336
output_db: ../output/TLL/PromptSensitivity/Texture/Qwen2-VL-7B-Instruct/TLL-Right-Texture.db
input_dir: ../data_local/tll/filtered_right_paths_100.txt
prompt: "Describe the texture of this image."
pooling_method: last
modules:
  - visual.merger
  - model.layers.0
  - model.layers.10
  - model.layers.20
  - model.layers.27
  - model.norm

